name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
    
    - name: Build
      run: gcc -o myapp src/myapp.c

    - name: Upload myapp for testing
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: ./myapp

  testing:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make check

    - name: Download myapp
      uses: actions/download-artifact@v2
      with:
        name: myapp

    - name: Unit Tests
      run: |
        gcc -o unit_test test/unit_test.c
        ./unit_test

    - name: Functional Tests
      run: bash ./tests/functional_test.sh

    - name: Integration Tests
      run: bash ./tests/integration_test.sh
    
    - name: System Tests
      run: bash ./tests/system_tests.sh
    
    - name: Performance Tests
      run: ./scripts/run_performance_tests.sh # 성능 테스트 스크립트 실행 예시